pipeline {

    agent any 
    stages{
        stage('Qemu') {
            steps{
                echo 'Start qemu'
                sh 'rm -rf romulus romulus.zip'
                sh 'rm -rf romulus romulus.zip.2'
                sh 'apt update'
                sh 'apt install -y qemu-system'
                sh 'apt install -y wget'
                sh 'apt install -y unzip'
                sh 'wget https://jenkins.openbmc.org/job/ci-openbmc/lastSuccessfulBuild/distro=ubuntu,label=docker-builder,target=romulus/artifact/openbmc/build/tmp/deploy/images/romulus/*zip*/romulus.zip'
                sh 'unzip -y romulus.zip'
                sh 'qemu-system-arm -m 256 -M romulus-bmc -nographic -drive file=romulus/obmc-phosphor-image-romulus-20250212052422.static.mtd,format=raw,if=mtd -net nic -net user,hostfwd=:0.0.0.0:2222-:22,hostfwd=:0.0.0.0:2443-:443,hostfwd=udp:0.0.0.0:2623-:623,hostname=qemu'

            }
        }
        stage('Auto') {
            steps{
                echo 'Start autotests'
            }

        }
        stage('WebUI') {
            steps{
                echo 'Start WebUI tests'
            }

        }
        stage('Locust') {
            steps{
                echo 'Start Locust tests'
            }
        }
    }
}